FROM openjdk:11
ADD microservice-book-0.0.1-SNAPSHOT.jar microservice-book-0.0.1-SNAPSHOT.jar
ADD wait-for-it.sh wait-for-it.sh
RUN chmod +x /wait-for-it.sh
#ENTRYPOINT ["java", "-jar", "microservice-0.0.1-SNAPSHOT.jar"]
